### ISSUE TITLE
Trailing parameter always includes `:`

### ISSUE THREAD

**Issue by AlMcKinlay** [Seldszar/tekko#3]
The final parameter passed into, when `parse` is called, will always be pre-pended by a `:`. This is, I think, technically allowed by the specification, but is adding on a lot of extra characters when not necessary.

It would be nice if it only added on the trailing `:` if it includes a space, which is all that is required.

**Comment by Seldszar** [comment]
You mean the method `format` instead, no?
If that's the case, yes, conditionally adding a trailing parameter is possible.

**Comment by AlMcKinlay** [comment]
Yeah, I did mean `format`, sorry, brain fart obviously.

Great, thanks for that addition, it cleans up my tests quite a bit :-P
